const reviews = [
  {
    id: 1,
    content: "Un service exceptionnel au Barber Bègles ! Je suis vraiment satisfait de ma coupe.",
    rating: 5,
    user_id: 1,
    service_id: 1,
    service_name: "Coupe",
    username: "Guillaume",
    date: new Date("2023-08-31"), 
  },
  {
    id: 2,
    content: "Le meilleur barber shop de la région ! L'équipe est très talentueuse et accueillante.",
    rating: 5,
    user_id: 2,
    service_id: 1,
    service_name: "Coupe",
    username: "Olivier",
    date: new Date("2023-08-30"), 
  },
  {
    id: 3,
    content: "Un endroit incontournable pour une expérience de coupe de cheveux de qualité.",
    rating: 5,
    user_id: 3,
    service_id: 2,
    service_name: "Coloration", 
    username: "David",
    date: new Date("2023-08-29"),
  },
  {
    id: 4,
    content: "Je recommande vivement le Barber Bègles. Les coiffeurs sont professionnels et sympathiques.",
    rating: 5,
    user_id: 4,
    service_id: 3,
    service_name: "Défrisage",
    username: "Paco",
    date: new Date("2023-08-28"), 
  },
  {
    id: 5,
    content: "Un service remarquable et une ambiance agréable. Mon nouveau barber shop préféré !",
    rating: 5,
    user_id: 5,
    service_id: 4,
    service_name: "Barbe",
    username: "Chris",
    date: new Date("2023-08-27"), 
  },
  {
    id: 6,
    content: "Les coiffeurs du Barber Bègles sont vraiment doués. Ils ont su réaliser exactement ce que je voulais.",
    rating: 5,
    user_id: 6,
    service_id: 5,
    service_name: "Soin Vapeur", 
    username: "John",
    date: new Date("2023-08-26"), 
  },
  {
    id: 7,
    content: "Je suis toujours satisfait de mes visites au Barber Bègles. Les résultats sont toujours impeccables.",
    rating: 5,
    user_id: 7,
    service_id: 6,
    service_name: "Épilation au fil",
    username: "Momo",
    date: new Date("2023-08-25"), 
  },
];

module.exports = reviews;


  
